version: '3.7'
services:
    wodss_backend:
        build: ./
        image: wodss/backend:latest
        container_name: wodss_backend
        restart: always
        ports:
          - "3090:3090"
        depends_on:
          - mongodb
    mongodb:
        image: mongo