version: '3.7'
services:
    wodss_backend:
        container_name: wodss_backend
        restart: always
        image: wodss/backend:latest
        ports:
          - "3000:3000"
        depends_on:
          - mongodb
    mongodb:
        image: mongo